spring:
  application:
    name: comapp-config
  rabbitmq:
    host: 192.168.1.93
    username: guest
    password: guest  
  profiles:
    active: dev 

server: 
  port: 5001

management: 
  security:
    enabled: false  # 使得/refresh不需要验权
security:  # 访问时需要提供用户和密码
  ignored: /monitor  # 这个接口不做用户名密码校验, /monitor接收git刷新通知
  user:  #连接config-server时的账户和密码
    name: user
    password: 12345678
encrypt:
  key: 12345678  # 加解密用的秘钥

wql: 
  eureka: 
    username: admin
    password: admin

eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   #服务列表缓存更新时间
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    lease-renewal-interval-in-seconds: 10  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）

# 不同环境的配置
---
spring:
  profiles: dev
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/   

---
spring:
  profiles: prod
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/     
      