spring:
  application:
    name: comapp-config
  profiles: 
    active: dev
  http: 
    encoding:
      force: true
      charset: UTF-8
      enabled: true  
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/wangqiulin/wql-cloud-config/
          searchPaths: properties
          username: 
          password: 
      label: master  

server: 
  port: 5001

wql: 
  eureka: 
    username: admin
    password: admin

eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   #服务列表缓存更新时间
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）

management:
  security:
    enabled: false #是否开启actuator安全认证


# 不同环境的配置
---
spring:
  profiles: dev
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/   

---
spring:
  profiles: prod
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@47.98.209.46:5000/eureka/     
      