eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/

server:
  port: 5002

spring:
  application:
    name: comapp-config
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/wangqiulin/wql-cloud-config/
          searchPaths: properties
          username: 
          password: 
      label: master   
