spring:
  application:
    name: comapp-config
  
  profiles:
    active: dev
    
  rabbitmq:
    host: 47.98.209.46
    username: wql
    password: wql
    
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/wangqiulin/wql-cloud-config/
          searchPaths: properties
          username: 
          password: 
      label: master  

server: 
  port: 5001

wql: 
  eureka: 
    username: admin
    password: admin

eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   #服务列表缓存更新时间
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    lease-renewal-interval-in-seconds: 10  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）

# 不同环境的配置
---
spring:
  profiles: dev
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@47.98.209.46:5000/eureka/   

---
spring:
  profiles: prod
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@47.98.209.46:5000/eureka/     
      