server:
  port: 6001

# eureka.instance.instance-id必须写在application.properties或application.yml中。不能写在bootstrap.properties和bootstrap.yml中。
eureka: 
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    leaseRenewalIntervalInSeconds: 10  # 心跳间隔
    lease-expiration-duration-in-seconds: 30  # 30秒未收到服务剔除服务 所有服务都需要加
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   # 服务列表缓存更新时间

spring: 
  application:
    name: service-user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#fegin连接超时[默认的ReadTimeout时间为5s，ConnectTimeout时间为2s. Fegin进行微服务间调用，底层用的还是Ribbon]
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1 

#熔断机制    
feign:
  hystrix:
    enabled: true

fegin:
  serviceId:
    order: service-order
    
        