eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
      
server:
  port: 6001
  
spring:
  application:
    name: service-user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#熔断机制    
feign:
  hystrix:
    enabled: true
    
        