eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    leaseRenewalIntervalInSeconds: 10  # 心跳间隔
    lease-expiration-duration-in-seconds: 30  # 30秒未收到服务剔除服务 所有服务都需要加
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   # 服务列表缓存更新时间
    serviceUrl: 
      defaultZone: http://127.0.0.1:5000/eureka/
      
server:
  port: 6001
  
spring:
  application:
    name: service-user
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#熔断机制    
feign:
  hystrix:
    enabled: true

fegin:
  serviceId:
    order: service-order
    
        