spring: 
  application:
    name: serviceapp-order
  profiles:
    active: dev 
    
server: 
  port: 6002
  
wql: 
  eureka: 
    username: admin
    password: admin  
  
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    leaseRenewalIntervalInSeconds: 10  # 心跳间隔
    lease-expiration-duration-in-seconds: 30  # 30秒未收到服务剔除服务 所有服务都需要加
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   # 服务列表缓存更新时间

---
spring:
  profiles: dev
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/
  
---
spring:
  profiles: prod
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/      
            
      
