spring:
  application:
    name: comapp-gateway
  profiles:
    active: dev  

server: 
  port: 5002

wql: 
  eureka: 
    username: admin
    password: admin      
      
zuul:
  routes:
    #用户服务
    api-user:  
      path: /user/**
      serviceId: serviceapp-user
    #公用服务  
    api-common:  
      path: /common/**
      serviceId: serviceapp-common   #如果出现中文文件名，上传文件的文件名会出现失败。访问的是指直接在这个/oss，前面加上"/zuul"，ok

#超时时间配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

      
eureka: 
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   # 服务列表缓存更新时间
      
---
spring: 
  profiles: dev
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/
      
---
spring: 
  profiles: prod
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@47.98.209.46:5000/eureka/  
      
                