spring:
  application:
    name: comapp-gateway
  profiles:
    active: dev  

server: 
  port: 5002

wql: 
  eureka: 
    username: admin
    password: admin      
      
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: service-user
    api-order:
      path: /api-order/**
      serviceId: service-order
      
eureka: 
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:@project.version@
    lease-renewal-interval-in-seconds: 10  #续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 90  #续约到期时间（默认90秒）
  client: 
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10   # 服务列表缓存更新时间
    healthcheck: 
      enabled: true  #开启健康检查
      
---
spring: 
  profiles: dev
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/
      
---
spring: 
  profiles: prod
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://${wql.eureka.username}:${wql.eureka.password}@127.0.0.1:5000/eureka/  
      
                